ДЗ №2 Список контактов и детали контакта (верстка и навигация)
Liannes/Android_J0 pull request #3
Opened 2021-10-18 17:15 UTC by Liannes

![Screenshot_1634575943](https://user-images.githubusercontent.com/77106080/137777304-9bc5b8eb-f3d6-4794-a8dc-b8046b8168a6.png)
![Screenshot_1634575946](https://user-images.githubusercontent.com/77106080/137777315-1375e704-2fdf-48b7-b0c8-cf11e98c2b01.png)

2021-10-20 21:13 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/MainActivity.kt
> +        setContactListFragment()
Эта функция должна вызываться только один раз за всё время работы приложения, а у тебя она будет вызываться при каждом повороте экрана. Чтобы этого не было, нужно сделать
if (savedInstanceState == null) {
            setContactListFragment()
        }

2021-10-20 21:15 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/MainActivity.kt
> +    private fun setContactListFragment(){
Речь идет о навигации, поэтому такие функции принято называть navigateToContactListFragment()

2021-10-20 21:16 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/MainActivity.kt
> +
Перед последней скобкой не может быть пустой строки

2021-10-20 21:18 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/MainActivity.kt
> +    private fun setContactDetailsFragment(){
navigateToContactDetailsFragment(contactId: String) {
Помним про передачу идентификатора контакта!

2021-10-20 21:19 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/MainActivity.kt
> +
Убрать пустую строку

2021-10-20 21:31 UTC, alex-sus commented on app/src/main/res/layout/contact_details_fragment.xml
> +            android:layout_width="120dp"
Все размеры необходимо вынести в ресурсы (dimens.xml), а здесь использовать их наименования.
Почитай, какие бывают ресурсы в Андроиде, в каких файлах они хранятся

2021-10-20 21:40 UTC, alex-sus commented on app/src/main/res/values/strings.xml
> +    <string name="num">Номер: </string>
Названия полей странные. Ты где-нибудь видел в официальных приложениях поле "Вторая почта"?
Назвать можно например так:
Телефон #1:
Телефон #2:
E-mail #1:
E-mail #2:
Совсем здорово будет, если ты научишься использовать стили для надписей и названия полей выводить например простым шрифтом, а их значения - жирным (т.е. они не должны быть на одно лицо, чтобы человек с первого взгляда их различал)

2021-10-20 21:48 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/ContactListFragment.kt
> +        requireActivity().setTitle(R.string.contact_list)
Непонятно, что у тебя с тулбаром.
На экранах необходимо использовать виджет Toolbar, которого у тебя сейчас вообще нет

2021-10-30 13:35 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/ContactListFragment.kt
> +        requireActivity().setTitle(R.string.contact_list)
+

2021-10-30 13:35 UTC, Liannes commented on app/src/main/res/layout/contact_list_fragment.xml
> +        </RelativeLayout>
+

2021-10-30 13:35 UTC, Liannes commented on app/src/main/res/layout/contact_details_fragment.xml
> +    </RelativeLayout>
+

2021-10-30 13:35 UTC, Liannes commented on app/src/main/res/layout/activity_main.xml
> +    <FrameLayout
+

2021-10-31 14:33 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/ContactListFragment.kt
> +            val transaction = requireActivity().supportFragmentManager.beginTransaction()
Перед сдачей приложение должно быть проверено на работоспособность. У тебя не происходит переход на экран детализации, а не происходит он потому, что ты почему-то не дописал обработку события onAttach, хотя это есть в материалах лекции и ты вроде даже где-то спрашивал о нем. 
Необходимо добавить:
override fun onAttach(context: Context) {
        super.onAttach(context)
        if (context is ContactInterface) {
            contactInterface= context
        }
    }

2021-10-31 14:43 UTC, KalimullinIlnaz requested changes

2021-10-31 14:43 UTC, KalimullinIlnaz commented on app/src/main/java/com/example/dz1_empty_pj/Constant.kt
> +class Constant {
лишнеее, пусть эта константа будет внутри компаньена
+ никогда так не пиши, то есть class и в нем только companion, используй сразу object

2021-10-31 14:43 UTC, KalimullinIlnaz commented on app/src/main/java/com/example/dz1_empty_pj/ContactDetailsFragment.kt
> +        val toolbar: androidx.appcompat.widget.Toolbar = view.findViewById(R.id.toolbar)
в импорты

2021-10-31 14:43 UTC, KalimullinIlnaz commented on app/src/main/res/layout/contact_details_fragment.xml
> +            android:id="@+id/exp_note"
названию view в camelCase

2021-10-31 14:43 UTC, KalimullinIlnaz commented on app/src/main/res/layout/contact_list_fragment.xml
> +                android:id="@+id/list_image"
аналогично везде, про названия вью

2021-10-31 15:10 UTC, alex-sus requested changes

2021-10-31 15:10 UTC, alex-sus commented on app/src/main/res/values/dimens.xml
> +    <dimen name="contact_details_name_Top">30sp</dimen>
Во всем файле напутаны размеры шрифтов и различные длины
1. Размеры шрифтов выражаются в sp, а длины - в dp
2. В файле необходимо сгруппировать их и хотя бы визуально, через пустую строку отделить размеры шрифтов от длин. А вообще я уже говорил тебе, что размеры шрифтов должны быть не здесь, а в стилях (style) и использоваться по правилам стилей.
3. Названия должны быть понятными - где шрифт, где длина. Например к названиям размеров шрифтов можно прибавлять ..._font_size

2021-10-31 15:10 UTC, alex-sus commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">DZ2_Empty_pj</string>
Зачем ты меняешь имя приложения? Оно должно оставаться постоянным, только ветки меняют имена

2021-10-31 15:52 UTC, alex-sus commented on app/src/main/res/values/dimens.xml
> +    <dimen name="contact_details_name_Top">30sp</dimen>
Кроме того, 
совет по стратегии наименования отступов между элементами экрана в файле dimens.xml
Отступы не должны относиться к каким-то элементам, они самостоятельные сущности.
Вынесение их в ресурсы дает возможность быстро изменять расположение вьюшек на экране, не разрушая при этом их композицию.
Поэтому при наименовании отступов будет логично придерживаться следующей системы:
- выделить для начала 3 размера: small, normal, big
- выделить два направления: vertical, horizontal
Тогда наименования будут выглядеть так:
small_vertical_margin, small_horizontal_margin,
normal_vertical_margin, normal_horizontal_margin,
big_vertical_margin, big_horizontal_margin
Всего лишь 6 универсальных отступов позволят тебе вполне гармонично сверстать любые несложные экраны, независимо от типов вьюшек на них, с возможностью быстрого масштабирования. Если нужно, типы размеров можно добавить: very_small, very_big
Понятно, что наиболее часто встречающийся размер отступа должен описываться типом normal

2021-10-31 16:06 UTC, alex-sus commented
Замечание по верстке экрана детализации:
- Поле с номером телефона почему-то привязано к верху экрана. Оно должно привязываться к низу аватара, как и соседнее с ним.
- Поля для второго номера телефона и второй эл.почты вообще отсутствуют. Необходимо добавить, правильно привязать, заполнить значениями для примера.
- По вертикали вьюшки должны привязываться к низу верхних вьюшек прямо над ними. И только самые верхние вьюшки привязываются к верху экрана.

2021-10-31 16:10 UTC, alex-sus commented on app/src/main/res/values/dimens.xml
> +    <dimen name="contact_details_name_Top">30sp</dimen>
И еще: размеры длин принято указывать четными числами (меньше погрешностей при масштабировании)

2021-10-31 16:35 UTC, Liannes commented on app/src/main/res/layout/contact_details_fragment.xml
> +            android:id="@+id/exp_note"
А можно по подробнее(пример), не особо понял
Да и я самоучка и мало, где встречал как так записывать

2021-10-31 16:58 UTC, alex-sus commented on app/src/main/res/layout/contact_details_fragment.xml
> +            android:id="@+id/exp_note"
Прочти это:
https://habr.com/ru/post/113044/
В этом твоем случае название у поля должно быть "@+id/expNote", однако я вообще не понимаю что это значит, следовательно название подобрано плохо. Я уже говорил - слова в названиях сокращать нельзя, максимум ты можешь использовать аббревиатуры, но не в этом случае.
Старайся давать названия системно, например всем заголовкам прибавлять в конце Header, неизменным надписям - Label, изменяемым надписям - TextView или Tv, картинкам - ImageView или Iv, кнопкам - Button и т.д.

2021-10-31 17:43 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/Constant.kt
> +        const val contactID = "CONTACT_ID"
done

2021-10-31 17:45 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/ContactDetailsFragment.kt
> +        fun newInstance(contactID: String? = null): ContactDetailsFragment {
done

2021-10-31 17:45 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/ContactInterface.kt
> +    fun navigationToContactDetailsFragment(contactID: String)
done

2021-11-01 13:00 UTC, Liannes commented
![Screenshot_1635771561](https://user-images.githubusercontent.com/77106080/139675410-cf2c8740-b630-43da-8a7f-d0e2c8e85b2d.png)
![Screenshot_1635771572](https://user-images.githubusercontent.com/77106080/139675441-a7b36c6e-b35d-4e2d-a0a8-37d56fed1c6f.png)

2021-11-01 13:01 UTC, Liannes commented
Насчет примечания во втором скрине, так и было задумано мной

2021-11-01 18:17 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/ContactDetailsFragment.kt
> +        val toolbar: androidx.appcompat.widget.Toolbar = view.findViewById(R.id.toolbar)
Проблема в том, что АС не находит toolbar так, и показывает ошибку

2021-11-01 18:29 UTC, alex-sus commented on app/src/main/res/values/dimens.xml
> +    <dimen name="contact_details_name_Top">30sp</dimen>
А зачем ты назвал строки в ресурсах в camal-стиле? Так нельзя, это не названия вьюшек.
Выше я написал ясно, как они должны выглядеть: small_vertical_margin, т.е. маленькими буквами, через пробел, это стандарт, обязательный к исполнению.
Пойми одну вещь: разработчик должен быть внимателен и выполнять задание предельно точно, никакой отсебятины. В противном случае ты будешь зря терять время на переделки. 
Приложение учебное, но мы учим тебя по настоящим стандартам разработки, которые применяем сами. 
Выполняй задание ТОЧНО, как написано.
Все строки в файлах dimens.xml и strings.xml переименовать в underscore-стиле (small_vertical_margin).
Чтобы они одновременно автоматически переименовывались в других файлах, нужно применять операцию Refactor -> Rename или нажимать Shift+F6

2021-11-01 18:33 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/ContactDetailsFragment.kt
> +        val toolbar: androidx.appcompat.widget.Toolbar = view.findViewById(R.id.toolbar)
![image](https://user-images.githubusercontent.com/79583896/139722771-d7da9784-7a15-4cd6-9b77-aa5e08b20859.png)

2021-11-01 18:34 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/ContactDetailsFragment.kt
> +        val toolbar: androidx.appcompat.widget.Toolbar = view.findViewById(R.id.toolbar)
Гитхаб к сожалению не желает показывать текст в угловых скобках

2021-11-01 18:39 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/ContactDetailsFragment.kt
> +        fun newInstance(contactID: String? = null): ContactDetailsFragment {
> о

Исправил переменную, просто чтобы не запушивать опять все
![image](https://user-images.githubusercontent.com/77106080/139723558-2bb065ec-14db-4801-93c9-399531c0f264.png)

2021-11-01 18:40 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/ContactDetailsFragment.kt
> +        fun newInstance(contactID: String? = null): ContactDetailsFragment {
Или лучше новый пуш сделать?

2021-11-01 18:44 UTC, Liannes commented
Теперь все должно быть гладко, да?

2021-11-01 18:54 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/ContactDetailsFragment.kt
> +        }
Функция должна выглядеть так:
fun newInstance(contactId: String) =
                ContactDetailsFragment().apply {
                    arguments = Bundle().apply {
                        putString(CONTACT_ID, contactId)
                }
            }

2021-11-01 19:08 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/ContactDetailsFragment.kt
> +        }
А можете рассказать почему именно так?

2021-11-01 19:16 UTC, Liannes commented
Исправил

2021-11-03 19:56 UTC, alex-sus approved these changes

2021-11-03 19:57 UTC, merged