ДЗ 3. Выделить привязанный сервис для загрузки списка контактов
Liannes/Android_J0 pull request #4
Opened 2021-11-07 21:49 UTC by Liannes

![Screenshot_1636321699](https://user-images.githubusercontent.com/77106080/140663047-bc37e428-e765-4f6e-a8e1-74eb2f145789.png)
![Screenshot_1636321702](https://user-images.githubusercontent.com/77106080/140663048-ea6dadf3-a7ff-44a1-83d6-7ea18582e245.png)

2021-11-07 21:50 UTC, Liannes commented
Хотел попросить мне помочь как мне оформить 
а именно это ContactDetailsFragment
`   override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val toolbar: Toolbar = view.findViewById(R.id.toolbar)
        toolbar.title = getString(R.string.contactDetails)

        val firstName: TextView = view.findViewById(R.id.detailsName)
        val lastName: TextView = view.findViewById(R.id.detailsLastName)
        val firstNumber: TextView = view.findViewById(R.id.exampleNum)
        val secondNumber: TextView = view.findViewById(R.id.exampleNumTwo)
        val firstEmail: TextView = view.findViewById(R.id.exampleEmail)
        val secondEmail: TextView = view.findViewById(R.id.exampleEmailTwo)
        val exampleNote: TextView = view.findViewById(R.id.exampleNote)

        firstName.text = SetContactDetailsData.detailsContactData.firstName
        lastName.text = SetContactDetailsData.detailsContactData.lastName
        firstNumber.text = SetContactDetailsData.detailsContactData.firstNumber
        secondNumber.text = SetContactDetailsData.detailsContactData.secondNumber
        firstEmail.text = SetContactDetailsData.detailsContactData.firstEmail
        secondEmail.text = SetContactDetailsData.detailsContactData.secondEmail
        exampleNote.text = SetContactDetailsData.detailsContactData.exampleNote
    }`
и также ContactListFragment
`    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val toolbar: Toolbar = view.findViewById(R.id.toolbar)
        toolbar.title = getString(R.string.contactList)

        val contactName: TextView? = view.findViewById(R.id.listName)
        val contactLastName: TextView? = view.findViewById(R.id.listLastName)
        val contactNumber: TextView? = view.findViewById(R.id.listMobile)

        contactName?.text = listContactData.contactName
        contactLastName?.text = listContactData.contactLastName
        contactNumber?.text = listContactData.contactNumber

        val cardView: CardView = view.findViewById(R.id.cardView)
        cardView.setOnClickListener {
            contactInterface?.navigationToContactDetailsFragment(SetContactDetailsData.detailsContactData.contactId)
        }
    }`

2021-11-08 17:45 UTC, alex-sus commented
Суть просьбы не ясна, чем тут можно помочь?
В современных приложениях так вообще не делается, почитай про View Binding и применяй его вместо всего этого

2021-11-08 18:06 UTC, Liannes commented
> Суть просьбы не ясна, чем тут можно помочь?
> В современных приложениях так вообще не делается, почитай про View Binding и применяй его вместо всего этого

Мне переделывать все приложение?

2021-11-08 18:07 UTC, alex-sus requested changes

2021-11-08 18:07 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/contactDetails/object/SetContactDetailsData.kt
> +        "Халлон",
Странная конструкция, зачем так громоздко? 
object здесь вообще лишний
Можно просто объявить переменную detailsContactData и задать ей значения, но лучше сразу создать список из 1 элемента:
val detailsContactData = listOf(
ContactDetailsData(
        "1",
        "Халлон",
        ...
        )
        )
И кстати, когда параметров много, необходимо их именовать (см. "именованные параметры котлин")

2021-11-08 18:12 UTC, alex-sus commented
Что касается View Binding это не переделка, а небольшая доработка.  View Binding разработчику изучить в любом случае необходимо, сейчас самый подходящий случай.
Насчет остального - я почему-то не вижу никаких следов асинхронности, которую требует ДЗ - без этого никак. Кстати я просил копировать текст ДЗ в первый комментарий, чтобы не искать его.

2021-11-09 15:25 UTC, Liannes commented
На этой стадии я сделал биндер
Но вот не могу понять, что я сделал не так, что при запуске приложения, все ок, все переходы есть, но вот, когда возвращаешься, то данные в cardView не отображаются(
нажал на CV->Детали->обратно->в cv пусто

2021-11-10 13:41 UTC, Liannes commented
Теперь вроде все верно?

2021-11-10 19:50 UTC, alex-sus commented
Передача данных сделана неверно.
Сейчас данные находятся во фрагментах и выводятся на экран напрямую. Сервис оказался совершенно ни при чем, из него никаких данных не приходит, что противоречит условиям задачи.
Нужно либо перенести данные из фрагментов прямо в сервис, либо всё таки сделать отдельный файл с object для них, как было сделано выше, но только назвать объект как-то точнее, например Constants.
Далее данные во фрагменты должны приходить из сервиса.

2021-11-10 20:26 UTC, alex-sus requested changes

2021-11-10 20:26 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/contactList/ContactListData.kt
> +)
Не хватает поля для аватара

2021-11-10 20:26 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/contactList/ContactListFragment.kt
> +            "Халлон",
Убрать данные из фрагмента

2021-11-10 20:26 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/contactList/ContactListFragment.kt
> +    }
Я уже говорил, что этот companion object здесь вообще не нужен, убери его

2021-11-10 20:26 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/contactList/ContactListFragment.kt
> +        binder.listMobile.text = listContactData[0].contactNumber
Данные из сервиса поступают в contactListData, а не в listContactData

2021-11-10 20:26 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/service/ContactService.kt
> +    suspend fun getContactDetails(): List<ContactDetailsData>? {
У функции getContactDetails должен быть аргумент - идентификатор контакта и данные эта функция должна выдавать с учетом этого идентификатора

2021-11-10 20:26 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/service/GetContactService.kt
> +    fun getService(): ContactService?
Для чего эта функция, если она нигде у тебя не используется?

2021-11-10 20:41 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/fragment/contactList/ContactListFragment.kt
> +    }
Так если убрать, тогда не будет работать в Майне инстанс

2021-11-18 13:09 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactListFragment.kt
> +        getContactService?.getService()?.getContactList(contactCallBack)
Я не понимаю в чем тут проблема
Программа просто не хочет попадать в getContactList
Выше есть пример callback, но не уверен, что он верно сделан

2021-11-20 11:06 UTC, alex-sus requested changes

2021-11-20 11:18 UTC, alex-sus commented
К сожалению ты неправильно понял задачу и даже схема работы твоего приложения неправильная.
Как должно быть:
Фрагментам нужно отобразить данные о контактах в своих вьюшках, но фрагменты как бы не имеют доступа к данным.
Доступ к данным имеет сервис, но он не умеет ничего отображать.
Задача состоит в том, чтобы заставить сервис и фрагменты взаимодействовать таким образом, что при старте активити биндится с сервисом, а когда пользователь тапает по фрагменту, фрагмент посылает ЗАПРОС на получение данных в сервис. Сервис запрошенные данные передает фрагменту, а фрагмент их отображает на экране.
У тебя сделано наоборот: почему-то вьюшки прокидываются в сервис и сервис показывает данные на экране. 
Это неправильно. Переделать по правильной схеме.

2021-11-20 11:38 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/data/Contacts.kt
> +        val lastName: String,
То есть получается, что и в деталях и в листе имя должно состоять сразу с имя+фамилия?

2021-11-20 11:44 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/data/Contacts.kt
> +        val contactId: Int,
Исправил

2021-11-20 11:44 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/data/ContactData.kt
> +            "+7(900)888-88-18",
Исправил

2021-11-20 11:45 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +        fun newInstance(contactId: Int) = ContactDetailsFragment().apply {
Исправил

2021-11-20 11:47 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/interface/ContactCallBack.kt
> +    fun getContactData(data: List<Contacts>)
Исправил

2021-11-20 11:47 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/interface/DetailsCallBack.kt
> +    fun getContactDetails(data: Contacts)
Исправил

2021-11-20 11:47 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/interface/GetService.kt
> +interface CallBack {
Исправил

2021-11-20 11:52 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/data/Contacts.kt
> +data class Contacts(
Исправил

2021-11-20 11:54 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/interface/ContactCallBack.kt
> +interface ContactCallBack {
Исправил

2021-11-20 12:13 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/data/Contacts.kt
> +        val lastName: String,
Получается так. Всё в одну строку, даже отчество

2021-11-20 12:14 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/data/Contacts.kt
> +        val lastName: String,
Исправил

2021-11-20 12:18 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +    private val detailsCallBack = object : DetailsCallBack {
Я правильно понял мысль?
Я должен в сервисе сделать передачу данных, а в фрагмент должен получить эти данные
То есть скажем сервис получил инфу Contact, то фрагмент details должен взять данные из Contact и присвоить их в вьюшкам? или же фрагмент должен взять данные метода сервиса с Сontact и передать их в вьюшки?

2021-11-20 12:24 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +    private val detailsCallBack = object : DetailsCallBack {
На мой взгляд ты написал одно и тоже разными словами.
Перефразируй свой вопрос, чтобы была ясна разница в смыслах.
Так же обрати внимание на последний комментарий на странице.

2021-11-20 12:29 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +    private val detailsCallBack = object : DetailsCallBack {
Ясно одно: этот объект detailsCallBack тебе не пригодится, не нужно его передавать в сервис

2021-11-20 12:42 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +    private val detailsCallBack = object : DetailsCallBack {
Получается, что я должен создать onViewCreated и в нем обратиться к через getService.getContactDetails с нужным мне айдишником, а сервис должен предоставить данные по этому айди 
Но просто из-за того, что айди это стринг, как мне получить нужный элемент данных?

2021-11-20 14:08 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +    private val detailsCallBack = object : DetailsCallBack {
"Но просто из-за того, что айди это стринг, как мне получить нужный элемент данных?"
Это тема "Поиск элемента в списке" которую ты в принципе должен был изучить самостоятельно.
Вкратце это выглядит так:
fun getContactById(contactId: String): Contact {
             return contactList.find { it.id == contactId }
    } 
    
    Чтобы восполнить пробелы знаний по спискам прочти это:
    http://developer.alexanderklimov.ru/android/kotlin/collection.php

2021-11-21 18:51 UTC, KalimullinIlnaz commented
Всё нормально реализовано через колбэки, нужно лишь обернуть в weakReference их и исправить другие мелкие недочеты

2021-11-23 19:38 UTC, Liannes commented
Переписал весь код с нуля, и не стал залезать в дебри в которых был дальше

2021-11-24 20:35 UTC, alex-sus commented
Мне интересно, ты перед сдачей проверяешь своё приложение на смартфоне?
Это обязательное действие. Если оно показывает, что что-то работает не так, необходимо добиться правильной работы и только потом выкладывать результат на Гитхаб.
У тебя после поворота экрана приложение практически не работает корректно, контакты не отображаются.
Это необходимо исправить.
Если что-то не получается - об этом нужно писать, а не выкладывать молча неработающий код.

2021-11-24 20:39 UTC, Liannes commented
> Мне интересно, ты перед сдачей проверяешь своё приложение на смартфоне?
> Это обязательное действие. Если оно показывает, что что-то работает не так, необходимо добиться правильной работы и только потом выкладывать результат на Гитхаб.
> У тебя после поворота экрана приложение практически не работает корректно, контакты не отображаются.
> Это необходимо исправить.
> Если что-то не получается - об этом нужно писать, а не выкладывать молча неработающий код.
> 

Честно, говоря я забываю тестировать ориентацию экрана

2021-11-24 20:56 UTC, alex-sus commented
Поворот экрана и работа приложения после этого - это первое, что ты должен проверить. Это - обязательно.
Проблема конкретно здесь состоит в том, что после поворота экрана сервис не успевает прибиндиться (это долгая операция) и соответственно данным прийти неоткуда. Выход в том, чтобы во фрагментах  ждать и проверять, подключился ли сервис и только после этого читать данные. 
Еще конкретнее это решается одной строкой с пустым циклом while:
while (!isServiceBound()) {}

2021-11-24 20:57 UTC, Liannes commented
> 

То есть по факту такую проверку надо делать всегда, когда работаешь с сервисами?

2021-11-24 20:58 UTC, alex-sus commented
Вот именно!

2021-11-24 21:40 UTC, Liannes commented
Вроде исправил, но все же вопрос
Почему надо делать именно пустую проверку? 
И я ведь правильно понял, что мне нужно передавать boolean с мейна?
Просто пока не понимаю, что так может порешать true или false

2021-11-25 18:37 UTC, alex-sus commented
Пустой while здесь просто ходит по кругу и задерживает выполнение программы, пока сервис не прибиндится.
Решение не самое красивое, но простое и надежное.
Если сможешь придумать лучшее решение, будешь молодец.

2021-11-25 18:46 UTC, alex-sus commented
Хорошо, идем дальше к следующему ДЗ.
Сразу хочу дать пояснение по фразе в нем "Необходимо добавить к деталям контакта поле "День рождения" в формате "число месяц".
Ее воспринимают как указание хранить только число и месяц рождения. Это не верно. Хранить нужно ПОЛНУЮ дату, включая год, а ВЫВОДИТЬ НА ЭКРАН только дату и месяц.
Далее, для хранения даты пытаются применять всякие самодельные кривые типы. Это путь к многочисленным проблемам в будущем. Даты ВСЕГДА храни в специальных типах, предназначенных конкретно для дат. В данном случае лучший выбор типа для поля даты рождения: GregorianCalendar - прочти о нем подробнее в Интернете, какие у него методы, как с ним правильно работать.

2021-11-25 18:46 UTC, alex-sus approved these changes

2021-11-25 18:47 UTC, merged