ДЗ 4 Напоминалка о дне рождения контакта
Liannes/Android_J0 pull request #5
Opened 2021-11-30 17:25 UTC by Liannes

Необходимо добавить к деталям контакта поле "День рождения" в формате "число месяц"

А так же кнопку которая будет иметь 2 состояния - "Включить напоминания" и "Выключить напоминания"
Состояние кнопки должно зависеть от того, добавлена ли уже задача в AlarmManager или нет.

При нажатии кнопки в состоянии "Включить напоминания" - должна ставиться задача на вызов вашего BroadcastReceiver'а на число в поле "День рождения" в качестве данных в Intent должен передаваться ID выбранного контакта и текст напоминания "Сегодня день рождения у $s", где $s - имя контакта
При нажатии кнопки в состоянии "Выключить напоминания" - должна производиться отмена предстоящей задачи в AlarmManager и состояние кнопки должно обновиться на "Включить напоминания"
https://developer.android.com/training/scheduling/alarms

Ваш BroadcastReceiver в свою очередь должен запустить Notification(Специальное уведомление, которое показывается в шторке уведомлений) с текстом пришедшем ему из Intent. https://developer.android.com/training/notify-user/build-notification

При нажатии пользователем на уведомление - должна запуститься активность вашего приложения, при этом должен сразу открыться экран с деталями контакта у которого день рождение, уведомление при этом должно исчезнуть из шторки уведомлений. Смотрите https://developer.android.com/reference/android/app/Activity#getIntent()

2021-12-02 15:51 UTC, alex-sus commented
Приложение вылетает на старте.
Я уже писал тебе, что не имеет смысла выкладывать на проверку неработающий вариант.
Сначала добейся, чтобы приложение работало и выполняло все пункты задания.

2021-12-02 16:01 UTC, alex-sus requested changes

2021-12-02 16:09 UTC, alex-sus commented
Меня интересует как ты проверил, что условия задачи выполняются?
А именно:
- Напоминания устанавливаются и отменяются.
- Напоминаний можно установить одновременно несколько, ведь потом контактов будет много.
- Напоминание появляется на экране в заданное время даже при выгруженном приложении.
- По нажатию на Напоминание происходит переход именно на экран с деталями указанного контакта, а не на список контактов.

Для проверки на реальном смартфоне предлагаю при установке напоминания к текущему времени программно прибавлять количество секунд, указанных в константе (которую нужно создать). Для начала пусть там будет 20 секунд. Таким образом, мы сможем легко проверить в реальности как срабатывает напоминание просто подождав несколько секунд - оно должно появится на экране даже при выгруженном приложении. Естественно в качестве даты рождения контакта нужно будет устанавливать текущую дату.

2021-12-02 16:22 UTC, Liannes commented
> Меня интересует как ты проверил, что условия задачи выполняются? А именно:
> 
> * Напоминания устанавливаются и отменяются.
> * Напоминаний можно установить одновременно несколько, ведь потом контактов будет много.
> * Напоминание появляется на экране в заданное время даже при выгруженном приложении.
> * По нажатию на Напоминание происходит переход именно на экран с деталями указанного контакта, а не на список контактов.
> 
> Для проверки на реальном смартфоне предлагаю при установке напоминания к текущему времени программно прибавлять количество секунд, указанных в константе (которую нужно создать). Для начала пусть там будет 20 секунд. Таким образом, мы сможем легко проверить в реальности как срабатывает напоминание просто подождав несколько секунд - оно должно появится на экране даже при выгруженном приложении. Естественно в качестве даты рождения контакта нужно будет устанавливать текущую дату.

Так я залил, не как итоговый вариант, а напрямую спросить вопросы, не брать же куски кода и говорить, что да как
и в таком случаи видны все косяки
Вопросы я как ревью оставил

2021-12-03 13:47 UTC, alex-sus commented
Не понял, какие у тебя сейчас есть вопросы?

2021-12-03 13:50 UTC, Liannes commented
> Не понял, какие у тебя сейчас есть вопросы?

В данные момент у меня вопрос в плане ресивера, я все же добился того, чтобы переключатель работал, но встретился с тем, что запрос intent появляется, но он не знает куда ему идти, это может быть связано с тем, что у меня extraString, а не extraInt в брокасте?

2021-12-03 23:24 UTC, Liannes commented
Сделал две проверки из 3
Все работает, но вот не понимаю, как мне правильно поймать уведомление в сервисе и переадресовать на контакта из списка в массиве
Я решил использовать так, но ничего не получается
```
         override fun onServiceConnected(name: ComponentName?, service: IBinder?) {
            val binder = service as ServerContact.ContactServiceBinder
            Log.i(tag, "Connect")
            serverContact = binder.getService()
            contactBound = true

            val fragment = intent.getStringExtra(BirthdayReceiver.FRAGMENT_LAYOUT)
            val contactId = intent.getStringExtra(CONTACT_ID)
            Log.d(tag, "fragment = $fragment + contactId = $contactId")

            if (fragment !== null) contactId?.let { navigationToContactDetailsFragment(it) }

            if (savedFirstFragment == true) navigationToContactListFragment()
        }
```
Но лог говорит, что получается в fragment null и пропускает метод

2021-12-05 11:23 UTC, alex-sus requested changes

2021-12-05 11:23 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/broadreciver/BroadReceiver.kt
> +        private const val CONTACT_ID = "contactId"
companion object не нужен. Все константы перенести выше, перед строкой class BroadReceiver : BroadcastReceiver()

2021-12-05 11:23 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/broadreciver/BroadReceiver.kt
> +            val notificationChannel = NotificationChannel(
Создание NotificationChannel должно происходить в MainActivity в onCreate. Перенести туда.

2021-12-05 11:23 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/broadreciver/BroadReceiver.kt
> +    private fun setAlarm(context: Context, contactId: String, reminder: String) {
Всю работу с AlarmManager нужно вынести в отдельный класс.
Лучше, если это будет inner class внутри фрагмента детализации

2021-12-05 11:23 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/broadreciver/BroadReceiver.kt
> +        notificationManager.notify(1, notification?.build())
Первый аргумент должен быть не "1", а например contactId.hashCode(), иначе у тебя будет невозможно установить несколько напоминаний одновременно

2021-12-05 11:33 UTC, Liannes commented
@alex-sus я весь код переписал, и он у меня теперь почти весь другой, если вечером загружу, сможет его прокомментировать?
Просто данный код теперь совсем не актуальный, но уточнения я понял

2021-12-05 11:34 UTC, alex-sus requested changes

2021-12-05 11:34 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/MainActivity.kt
> +            val contactId: String = intent.getStringExtra("contactId").toString()
Неверное обращение к экстра.
"contactId" и "contactDetails" должны быть в константах, и в ресивере должны использоваться эти же константы

2021-12-05 11:38 UTC, alex-sus commented
Не нужно ждать разрешений от меня на загрузку решения задачи на гитхаб.
Если ты сделал свой вариант, ПРОВЕРИЛ ЕГО НА СМАРТФОНЕ И ОН РАБОТАЕТ - сразу выкладывай

2021-12-05 17:12 UTC, Liannes commented
Это мой полностью переписанный код, только я перенес константы наверх, но тут не проходит одна проверка
При открытии уведомления не кидает в Детали контакта, остальное все хорошо

2021-12-05 19:36 UTC, alex-sus commented
На этот раз код даже не компилируется. 
Запомни железное правило: после ЛЮБОЙ правки код нужно компилировать (CTRL + F9 или SHIFT + F10), прежде чем пушить.

2021-12-05 19:40 UTC, Liannes commented
> На этот раз код даже не компилируется. 
> Запомни железное правило: после ЛЮБОЙ правки код нужно компилировать (CTRL + F9 или SHIFT + F10), прежде чем пушить.

Простите, это моя невнимательность, только после того как запушил заметил

2021-12-05 19:46 UTC, Liannes commented
> На этот раз код даже не компилируется. 
> Запомни железное правило: после ЛЮБОЙ правки код нужно компилировать (CTRL + F9 или SHIFT + F10), прежде чем пушить.

Запомнил

2021-12-05 20:52 UTC, alex-sus commented
А почему не все замечания выше исправлены?

2021-12-05 20:56 UTC, Liannes commented
> А почему не все замечания выше исправлены?

Некоторые замечание стали не актуальными, да и может заметили еще что, вот и загрузил

2021-12-05 21:10 UTC, alex-sus requested changes

2021-12-05 21:10 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/MainActivity.kt
> +            val fragment = intent.getStringExtra(FRAGMENT_LAYOUT)
Зачем нужен fragment ?

2021-12-05 21:10 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +    @SuppressLint("SetTextI18n")
А это еще зачем?

2021-12-05 21:10 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +                            data?.birthDay?.get(GregorianCalendar.MONTH).toString()
Во-первых месяц у тебя показывается на экране неправильно - в этом типе месяцы считаются с нуля.
Во-вторых Calendar умеет выводить названия месяцев буквами и по-русски.

2021-12-05 21:19 UTC, alex-sus commented
Я не вижу проверки того, что уведомление о ДР уже установлено - при выходе из приложения и обратном заходе индикатор сбрасывается.
Кроме того при установке аларма не заметно учета високосного года.

"При открытии уведомления не кидает в Детали контакта" - ты думаешь это должно произойти само собой? Где у тебя учитывается, было приложение запущено с ярлыка на экране или из Notification?

2021-12-08 11:49 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/BirthdayReceiver.kt
> +        val contactId = intent.getIntExtra(CONTACT_ID, 0)
Ну если так не сделать, то в 

```
val movePendingIntent = PendingIntent.getBroadcast(
            context,
            contactId,
            intent,
            PendingIntent.FLAG_UPDATE_CURRENT
        )
```
contactId будет подсвечен ошибкой, ну можно добавить getInt, но что-то мне подсказиывает, что это не будет решением проблемы

2021-12-08 11:49 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/BirthdayReceiver.kt
> +            val notificationChannel =
Вместе с менеджером?

2021-12-10 06:51 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/BirthdayReceiver.kt
> +            val notificationChannel =
А ты изучил тему Notification?
NotificationChannel достаточно создать всего 1 раз за время жизни приложения. Все последующие попытки просто игнорируются. Обращение к каналу идет по его CHANNEL_ID.
Канал создается в MainActivity, а в ресивере его создавать уже просто напросто незачем - используется созданный по CHANNEL_ID

2021-12-13 16:16 UTC, Liannes commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +                            data?.birthDay?.get(GregorianCalendar.MONTH).toString()
А как можно вывести русскими словами? У меня только получилось вывести англ название, просто интересно, для поднятие основ

2021-12-13 16:21 UTC, Liannes commented
Вы как-то говорили, что можно выводить месяц русскими буквами, а как это правильно сделать? 
В интернете, я только нашёл как выводить на английском, но даже на сыте oracle не написано, как выводить русскими словами месяц
```
fun currectData(date: GregorianCalendar): String { val format = SimpleDateFormat("dd.MMM") 
format.calendar = date
 return format.format(date.time)}
```

2021-12-13 20:12 UTC, alex-sus commented
Не понял при чем тут оракл.
Месяц по-русски выводится так:
birthday?.getDisplayName(
                                    Calendar.MONTH,
                                    Calendar.LONG,
                                    Locale.getDefault()
                            )

2021-12-13 20:57 UTC, Liannes commented
Проверьте последний мой пуш, все ли там правильно?
Все выводится и при открытии уведомлении показывается нужный контакт
Но вот насчет високосного года я не совсем уверен, что мой метод поможет, потому что правильно проверить сложно

2021-12-13 21:04 UTC, Liannes commented
> Не понял при чем тут оракл. Месяц по-русски выводится так: birthday?.getDisplayName( Calendar.MONTH, Calendar.LONG, Locale.getDefault() )

Все гуд сделал, просто чет вспомнил, что на эмуляторе не поменял язык, вот и месяц был на английском

2021-12-13 21:09 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +    inner class CurrectTime {
Опечатка в названии класса

2021-12-13 21:09 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +            data?.birthDay?.get(Calendar.YEAR)?.let { notificationCalendar.set(Calendar.YEAR, it) }
К чему все эти сложности?
Почему не просто val notificationCalendar = data?.birthDay

2021-12-13 21:09 UTC, alex-sus commented on app/src/main/java/com/example/dz1_empty_pj/fragment/ContactDetailsFragment.kt
> +            if(leap == true) notificationCalendar.add(Calendar.YEAR,4)
А если сегодня 14 января високосного года? Всё равно ДР на 4 года отодвинем?

2021-12-13 21:14 UTC, alex-sus commented
Есть ошибки и при работе с датой и при установке/снятии уведомлений, часть моих замечаний ты пропускаешь мимо ушей.
Однако я пропущу тебя к следующему ДЗ, чтобы на реальных контактах ошибки стали очевиднее

2021-12-13 21:15 UTC, merged